all:
  hosts:
    master:
      ansible_host: 10.0.5.11
      ip: 10.0.5.11
      access_ip: 10.0.5.11
    node1:
      ansible_host: 10.0.6.17
      ip: 10.0.6.17
      access_ip: 10.0.6.17
    node2:
      ansible_host: 10.0.7.33
      ip: 10.0.7.33
      access_ip: 10.0.7.33
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
